version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: linetwstock/fastapi:dev
    container_name: linetwstock_fastapi
    env_file: ./.env
    ports: 
      - '9001:8080'
