version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      # [Optional] Python version. e.g. 3.9.7-bullseye
      args:
        VARIANT: 3.9-bullseye
    image: linebot:dev
    container_name: linebot_app
    volumes:
      - ..:/home/vscode/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:cached
      - ~/.ssh:/home/vscode/.ssh
    working_dir: /home/vscode/workspace
    tty: true
